[project]
name = "textadventure-engine"
version = "0.1.0"
description = "Una libreria python per la creazione di piccoli minigiochi testuali."
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Giovanni Benedetto Galeazzi" }
]
license = { file = "LICENSE" }

dependencies = []

[project.urls]
Homepage = "https://github.com/tuo-username/textadventure-engine"
Repository = "https://github.com/tuo-username/textadventure-engine"

[tool.pytest.ini_options]
pythonpath = "src"
addopts = "-ra"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
