[project]
name = "textadventure"
version = "1.0.0"
description = "Una librerie per creare una piccola avventura testuale."
authors = [
    { name = "Giovanni Benedetto Galeazzi" }
]
readme = "README.md"
requires-python = ">=3.10"
license = { text = "Apache-2.0" }

dependencies = []

[project.optional-dependencies]
dev = [
    "pytest",
    "sphinx",
    "furo"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
